export const API_CONFIG = {
  BASE_URL: 'https://server.aimliedc.tech/h4b-backend',
  ENDPOINTS: {
    AUTH: '/auth',
    HACKATHON: '/hackathon',
    REGISTER: '/register',
    TEAM: '/team',
  },
} as const;

export const API_URLS = {
  REQUEST_OTP: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}?option=request`,
  VERIFY_OTP: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}?option=verify`,
  UPDATE_NAME: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}?option=update-name`,
  CREATE_HACKATHON: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.HACKATHON}?option=create`,
  UPDATE_HACKATHON: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.HACKATHON}?option=manage`,
  FETCH_MY_HACKATHONS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.HACKATHON}?option=fetch-my-hackathons`,
  FETCH_SINGLE_HACKATHON: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.HACKATHON}?option=fetch-single`,
  FETCH_ALL_HACKATHONS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.HACKATHON}?option=fetch-all`,
  REGISTER_FOR_HACKATHON: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.REGISTER}?option=register`,
  CREATE_TEAM: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.TEAM}?option=create-team`,
  JOIN_TEAM: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.TEAM}?option=join-team`,
  SUBMIT_TEAM: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.TEAM}?option=submit-team`,
  CHECK_TEAM_PRESENCE: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.TEAM}?option=check-team-presence`,
} as const;